import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Alkatra } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/page-sections/navbar";
import { SessionProvider } from "next-auth/react";
import Breadcrumb from "@/components/page-sections/breadcrumbs";
import ModalManager from "@/components/page-sections/modal-manager";
import { Toaster } from "@/components/ui/sonner";
import { db } from "@/db/client";
import { userRole, users } from "@/db/schema";
import { eq } from "drizzle-orm";
import { auth } from "@/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const interSans = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const fontAlkatra = Alkatra({
  variable: "--font-alkatra",
  subsets: ["latin"],
  weight: ["400", "500", "700", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const userId = session?.user?.id;

  let userRole: "Seller" | "Buyer";

  if (userId) {
    const roleData = await db
      .select({ role: users.role })
      .from(users)
      .where(eq(users.id, userId));
    userRole = roleData[0].role;
  } else {
    userRole = "Buyer";
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${fontAlkatra.variable} ${interSans.variable} antialiased`}
      >
        <SessionProvider>
          <Navbar userRole={userRole} />
        </SessionProvider>
        {/* <Navbar2 /> */}

        <Breadcrumb />
        <ModalManager />
        <Toaster />
        <main>{children}</main>
      </body>
    </html>
  );
}
