import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Alkatra } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/page-sections/navbar";
import { SessionProvider } from "next-auth/react";
import Breadcrumb from "@/components/page-sections/breadcrumbs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const interSans = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const fontAlkatra = Alkatra({
  variable: "--font-alkatra",
  subsets: ["latin"],
  weight: ["400", "500", "700", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${fontAlkatra.variable} ${interSans.variable} antialiased`}
      >
        <SessionProvider>
          <Navbar />
        </SessionProvider>
        {/* <Navbar2 /> */}

        <Breadcrumb />
        <main>{children}</main>
      </body>
    </html>
  );
}
