import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Alkatra } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const interSans = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const fontAlkatra = Alkatra({
  variable: "--font-alkatra",
  subsets: ["latin"],
  weight: ["400", "500", "700", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // If you find the user as seller, send him directly to the dashboard
  return (
    <html lang="en">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              var initOpts = {
                projectKey: "BrLftvYDIrikjebtG0WR",
                ingestPoint: "https://sonarly.dev/ingest",
                __DISABLE_SECURE_MODE: window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1'
              };
              var startOpts = {};
              
              (function(A,s,a,y,e,r){
                r=window.Sonarly=[e,r,y,[s-1, e]];
                s=document.createElement('script');s.src=A;s.async=!a;
                document.getElementsByTagName('head')[0].appendChild(s);
                r.start=function(v){r.push([0])};
                r.stop=function(v){r.push([1])};
                r.setUserID=function(id){r.push([2,id])};
                r.setUserAnonymousID=function(id){r.push([3,id])};
                r.setMetadata=function(k,v){r.push([4,k,v])};
                r.event=function(k,p,i){r.push([5,k,p,i])};
                r.issue=function(k,p){r.push([6,k,p])};
                r.isActive=function(){return false};
                r.getSessionToken=function(){};
              })("https://sonarly.dev/static/tracker.js",1,0,initOpts,startOpts);
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${fontAlkatra.variable} ${interSans.variable} antialiased`}
      >
        <Toaster />
        <main>{children}</main>
      </body>
    </html>
  );
}